1: 1-good-sentences-wordsplit.hs WdPinyinGloss.hs Load.hs
	mkdir -p build; ghc -O2 -Wall -cpp -o 1 --make 1-good-sentences-wordsplit \
		-hidir build -odir build

2: 2.hs WdPinyinGloss.hs
	mkdir -p build; ghc -O2 -Wall -cpp -o 2 --make 2 \
		-hidir build -odir build
